declare const styles: {
  readonly "active": string;
  readonly "fadeIn": string;
  readonly "fadeOut": string;
  readonly "items": string;
  readonly "links": string;
  readonly "logout": string;
  readonly "menu": string;
  readonly "navbar": string;
  readonly "navlinks": string;
  readonly "navuser": string;
  readonly "nouser": string;
  readonly "opacity0": string;
  readonly "overlay": string;
  readonly "popupmenu": string;
  readonly "popupmenusettings": string;
  readonly "rotate": string;
  readonly "rotateminus": string;
  readonly "slideIn": string;
  readonly "slideOut": string;
  readonly "user": string;
  readonly "usercontainer": string;
  readonly "userdatacontainer": string;
  readonly "userinfo": string;
  readonly "useroverlay": string;
  readonly "userpopup": string;
  readonly "userpopuser": string;
};
export = styles;

